trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: docker volume create --name=sqlserverdata
  - bash: docker volume create --name=rabbitmqdata
  - bash: docker-compose build --force-rm
- job: test
  displayName: Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: docker-compose up -d
  - bash: docker exec tests dotnet test
